services:
  client:
    container_name: "dockview-client"
    image: "dockview-client:development"
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile.dev
    volumes:
      - .:/app
      - ${PNPM_STORE_PATH}:/root/.local/share/pnpm/store
      - turbo_cache:/app/.turbo
    env_file:
      - ./apps/client/config/.env.development
    ports:
      - "3100:3100"
      - "24678:24678"
    networks:
      dockview_network:
        ipv4_address: 172.18.0.3

  backend:
    container_name: "dockview-service"
    image: "dockview-service:development"
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.dev
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PNPM_STORE_PATH}:/root/.local/share/pnpm/store
      - turbo_cache:/app/.turbo
    env_file:
      - ./apps/backend/config/.env.development
    ports:
      - "8080:8080"
      - "4100:4100"
    networks:
      dockview_network:
        ipv4_address: 172.18.0.2 # Static IP for the Node.js app

volumes:
  turbo_cache:

networks:
  dockview_network:
    driver: bridge
    name: dockview_internal
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
