services:
  client:
    container_name: "dockview-client"
    image: "dockview-client:development"
    build:
      context: ./dockview-client
      dockerfile: Dockerfile.dev
    volumes:
      - ./dockview-client:/app
    env_file:
      - ./dockview-client/config/.env.development
    ports:
      - "3100:3100"
    networks:
      dockview_network:
        ipv4_address: 172.18.0.3

  backend:
    container_name: "dockview-service"
    image: "dockview-service:development"
    build:
      context: ./dockview-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./dockview-service:/app
      - ./dockview-ws:/dockview-ws
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./dockview-service/config/.env.development
    ports:
      - "8080:8080"
      - "4100:4100"
    networks:
      dockview_network:
        ipv4_address: 172.18.0.2 # Static IP for the Node.js app

networks:
  dockview_network:
    driver: bridge
    name: dockview_internal
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
