services:
  client:
    container_name: "dockview-client"
    image: "dockview-client:development"
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/client/node_modules
      - /app/packages/ws/node_modules
      - /app/packages/core/node_modules
      - /app/packages/ui/node_modules
      - /app/packages/config-typescript/node_modules
    env_file:
      - ./apps/client/config/.env.development
    ports:
      - "3100:3100"
      - "24678:24678"
    networks:
      dockview_network:
        ipv4_address: 172.18.0.3

  backend:
    init: true
    container_name: "dockview-service"
    image: "dockview-service:development"
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/apps/backend/node_modules
      - /app/packages/ws/node_modules
      - /app/packages/react-ssr/node_modules
      - /app/packages/core/node_modules
      - /app/packages/ui/node_modules
      - /app/packages/config-typescript/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./apps/backend/config/.env.development
    ports:
      - "8080:8080"
      - "4100:4100"
    networks:
      dockview_network:
        ipv4_address: 172.18.0.2

networks:
  dockview_network:
    driver: bridge
    name: dockview_internal
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
