FROM node:lts-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm i --only=production

COPY . .
RUN npm run build

FROM node:lts-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci --only=production

COPY --from=builder /app/build ./build
COPY --from=builder /app/public ./public
COPY --from=builder /app/server.js ./server.js

EXPOSE 3000

CMD ["npm", "start"]